# Cash And Receivables

**Selected Brief Excercises**

Intermediate Accounting 18th Edition

Kieso, Weygant, Warfield

In [8]:
import os
import sys
import pandas as pd
from datetime import date
from IPython.display import display, HTML

mod_path = os.path.abspath(os.path.join(".."))
if mod_path not in sys.path:
    sys.path.append(mod_path)

from ledger import Ledger
from helpers import months_elapsed, format_ledger_table

---

##### **BE6.1 (LO 1) Kraft Enterprises owns the following assets at December 31, 2025.**

| Description | Amount |
| --- | ---: |
| Cash in bank—savings account | $68,000 | 
| Cash on hand | 9,300 | 
| Cash refund due from IRS | 31,400 | 
| Checking account balance | 17,000 | 
| Postdated checks | 750 | 
| Certificate of deposit (180-days) | 90,000 | 

What amount should be reported as cash?

In [1]:
cash = {
    "savings_account": 68000,
    "on_hand": 9300,
    "checking_account": 17000,
}

print(f"Cash Balance: $ {sum(cash.values()):,.0f}")

Cash Balance: $ 94,300

---

##### **BE6.2 (LO 2) Restin Co. uses the gross method to record sales made on credit. On June 1, 2025, it made sales of 50,000 with terms 3/15, n/45. On June 12, 2025, Restin received full payment for the June 1 sale. Prepare the required journal entries for Restin Co**

In [11]:
discount = .03
sales = 50000
discounted_sales = 0
sales_discount = 0
sales_date = date(2025, 6, 1)
payment_date = date(2025, 6, 12)
days = (payment_date - sales_date).days

if days <= 15:
    sales_discount = sales * discount 
    discounted_sales = sales - sales_discount

restin = Ledger()
restin.reset()

restin.add_entry(
    [
        {"date": "2025-6-1", "account": "Accounts Receivable", "debit": sales, "credit": 0},
        {"date": "2025-6-1", "account": "Sales Revenue", "debit": 0, "credit": sales},
    ],
    description="",
)

restin.add_entry(
    [
        {"date": "2025-6-12", "account": "Cash", "debit": discounted_sales, "credit": 0},
        {"date": "2025-6-12", "account": "Sales Discounts", "debit": sales_discount, "credit": 0},
        {"date": "2025-6-12", "account": "Accounts Receivable", "debit": 0, "credit": sales},
    ],
    description="",
)

display(HTML(format_ledger_table(restin).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

---

##### **BE6.3 (LO 2) Use the information from BE6.2, assuming Restin Co. uses the net method to account for cash discounts. Prepare the required journal entries for Restin Co.**

In [12]:
sales_discount = sales * discount 
discounted_sales = sales - sales_discount

restin = Ledger()
restin.reset()

restin.add_entry(
    [
        {"date": "2025-6-1", "account": "Accounts Receivable", "debit": discounted_sales, "credit": 0},
        {"date": "2025-6-1", "account": "Sales Revenue", "debit": 0, "credit": discounted_sales},
    ],
    description="",
)

restin.add_entry(
    [
        {"date": "2025-6-12", "account": "Cash", "debit": discounted_sales, "credit": 0},
        {"date": "2025-6-12", "account": "Accounts Receivable", "debit": 0, "credit": discounted_sales},
    ],
    description="",
)

display(HTML(format_ledger_table(restin).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

---

##### **BE6.4 (LO 2) Roeher Company sold 9,000 of its specialty shelving to Elkins Office Supply Co. on account.**

**Prepare the entries when:**
- (a) Roeher makes the sale, 
- (b) Roeher grants an allowance of 700 when some of the shelving does not meet exact specifications but still could be sold by Elkins, and 
- (c) at year-end; Roeher estimates that an additional 200 in allowances will be granted to Elkins.

In [12]:
roeher = Ledger()
roeher.reset()

sales = 9000
allowance = 700
additional_allowance = 200

roeher.add_entry(
    [
        {"date": "2025-6-1", "account": "Accounts Receivable", "debit": sales, "credit": 0},
        {"date": "2025-6-1", "account": "Sales Revenue", "debit": 0, "credit": sales},
    ],
    description="To record sale of shelving to Elkins",
)

roeher.add_entry(
    [
        {"date": "2025-6-15", "account": "Sales Returns and Allowances", "debit": allowance, "credit": 0},
        {"date": "2025-6-15", "account": "Accounts Receivable", "debit": 0, "credit": allowance},
    ],
    description="To grant allowance to Elkins for error in specifications.",
)

roeher.add_entry(
    [
        {"date": "2025-12-31", "account": "Sales Returns and Allowances", "debit": additional_allowance, "credit": 0},
        {"date": "2025-12-31", "account": "Accounts Receivable", "debit": 0, "credit": additional_allowance},
    ],
    description="To record estimated allowances for Elkins.",
)
display(HTML(format_ledger_table(roeher).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1 — To record sale of shelving to Elkins
Saved transaction id 2 — To grant allowance to Elkins for error in specifications.
Saved transaction id 3 — To record estimated allowances for Elkins.

---

##### **BE6.5 (LO 3) Wilton, Inc. had net sales in 2025 of 1,400,000. At December 31, 2025, before adjusting entries, the balances in selected accounts were Accounts Receivable 250,000 debit, and Allowance for Doubtful Accounts 2,400 credit. If Wilton estimates that 8% of its receivables will prove to be uncollectible, prepare the December 31, 2025, journal entry to record bad debt expense.**

In [22]:
probability = .08
accounts_receivable = 250000 
allowance_for_doubtful_accounts = -2400 # Credit
estimated_allowance = accounts_receivable * probability
print(f"The estimated Allowance for Doubtful Account is: $ {estimated_allowance:,.0f}\n")
bad_debt_expense = estimated_allowance + allowance_for_doubtful_accounts

wilton = Ledger()
wilton.reset()

wilton.add_entry(
    [
        {"date": "2025-12-31", "account": "Bad Debt Expense", "debit": bad_debt_expense, "credit": 0},
        {"date": "2025-12-31", "account": "Allowance for Doubtful Accounts", "debit": 0, "credit": bad_debt_expense},
    ],
    description="To record bad debt expense for the year.",
)
display(HTML(format_ledger_table(wilton).to_html(index=False)))

The estimated Allowance for Doubtful Account is: $ 20,000

Ledger has been reset.
Saved transaction id 1 — To record bad debt expense for the year.

---

##### **BE6.6 (LO 3) Use the information presented in BE6.5 for Wilton, Inc.**

- **a. Instead of an Allowance for Doubtful Accounts Balance of 2,400 credit, the balance was 1,900 debit. Assume that 10% of accounts receivable will prove to be uncollectible. Prepare the entry to record bad debt expense.**

In [21]:
probability = .10
accounts_receivable = 250000 
allowance_for_doubtful_accounts = 1900 # Debit
estimated_allowance = accounts_receivable * probability
print(f"The estimated Allowance for Doubtful Account is: $ {estimated_allowance:,.0f}\n")
bad_debt_expense = estimated_allowance - allowance_for_doubtful_accounts

wilton = Ledger()
wilton.reset()

wilton.add_entry(
    [
        {"date": "2025-12-31", "account": "Bad Debt Expense", "debit": bad_debt_expense, "credit": 0},
        {"date": "2025-12-31", "account": "Allowance for Doubtful Accounts", "debit": 0, "credit": bad_debt_expense},
    ],
    description="To record bad debt expense for the year.",
)
display(HTML(format_ledger_table(wilton).to_html(index=False)))

The estimated Allowance for Doubtful Account is: $ 25,000

Ledger has been reset.
Saved transaction id 1 — To record bad debt expense for the year.

- **b. Instead of estimating uncollectibles based on a percentage of receivables, assume Wilton prepares an aging schedule that estimates total uncollectible accounts at 24,600. (Assume an allowance of 2,400 credit.) Prepare the entry to record bad debt expense.**

In [20]:
allowance_for_doubtful_accounts = -2400 # credit
estimated_allowance = 24600
print(f"The estimated Allowance for Doubtful Account is: $ {estimated_allowance:,.0f}\n")
bad_debt_expense = estimated_allowance + allowance_for_doubtful_accounts

wilton = Ledger()
wilton.reset()

wilton.add_entry(
    [
        {"date": "2025-12-31", "account": "Bad Debt Expense", "debit": bad_debt_expense, "credit": 0},
        {"date": "2025-12-31", "account": "Allowance for Doubtful Accounts", "debit": 0, "credit": bad_debt_expense},
    ],
    description="To record bad debt expense for the year.",
)
display(HTML(format_ledger_table(wilton).to_html(index=False)))

The estimated Allowance for Doubtful Account is: $ 24,600

Ledger has been reset.
Saved transaction id 1 — To record bad debt expense for the year.

---