# Cash And Receivables

**Selected Brief Excercises**

Intermediate Accounting 18th Edition

Kieso, Weygant, Warfield

In [31]:
import os
import sys
import pandas as pd
from datetime import date
from IPython.display import display, HTML

mod_path = os.path.abspath(os.path.join(".."))
if mod_path not in sys.path:
    sys.path.append(mod_path)

from ledger import Ledger
from helpers import months_elapsed, format_ledger_table

from stackCalc import RPNEngine

**Note:** Some of the exercises in this Notebook are solved using my RPN financial calculator.  Click below to learn more.

- **[StackCalc](https://www.github.com/ekmartinez/StackCalc)**

---

##### **BE6.1 (LO 1) Kraft Enterprises owns the following assets at December 31, 2025.**

| Description | Amount |
| --- | ---: |
| Cash in bank—savings account | $68,000 | 
| Cash on hand | 9,300 | 
| Cash refund due from IRS | 31,400 | 
| Checking account balance | 17,000 | 
| Postdated checks | 750 | 
| Certificate of deposit (180-days) | 90,000 | 

What amount should be reported as cash?

In [1]:
cash = {
    "savings_account": 68000,
    "on_hand": 9300,
    "checking_account": 17000,
}

print(f"Cash Balance: $ {sum(cash.values()):,.0f}")

Cash Balance: $ 94,300

---

##### **BE6.2 (LO 2) Restin Co. uses the gross method to record sales made on credit. On June 1, 2025, it made sales of 50,000 with terms 3/15, n/45. On June 12, 2025, Restin received full payment for the June 1 sale. Prepare the required journal entries for Restin Co**

In [11]:
discount = .03
sales = 50000
discounted_sales = 0
sales_discount = 0
sales_date = date(2025, 6, 1)
payment_date = date(2025, 6, 12)
days = (payment_date - sales_date).days

if days <= 15:
    sales_discount = sales * discount 
    discounted_sales = sales - sales_discount

restin = Ledger()
restin.reset()

restin.add_entry(
    [
        {"date": "2025-6-1", "account": "Accounts Receivable", "debit": sales, "credit": 0},
        {"date": "2025-6-1", "account": "Sales Revenue", "debit": 0, "credit": sales},
    ],
    description="",
)

restin.add_entry(
    [
        {"date": "2025-6-12", "account": "Cash", "debit": discounted_sales, "credit": 0},
        {"date": "2025-6-12", "account": "Sales Discounts", "debit": sales_discount, "credit": 0},
        {"date": "2025-6-12", "account": "Accounts Receivable", "debit": 0, "credit": sales},
    ],
    description="",
)

display(HTML(format_ledger_table(restin).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

---

##### **BE6.3 (LO 2) Use the information from BE6.2, assuming Restin Co. uses the net method to account for cash discounts. Prepare the required journal entries for Restin Co.**

In [12]:
sales_discount = sales * discount 
discounted_sales = sales - sales_discount

restin = Ledger()
restin.reset()

restin.add_entry(
    [
        {"date": "2025-6-1", "account": "Accounts Receivable", "debit": discounted_sales, "credit": 0},
        {"date": "2025-6-1", "account": "Sales Revenue", "debit": 0, "credit": discounted_sales},
    ],
    description="",
)

restin.add_entry(
    [
        {"date": "2025-6-12", "account": "Cash", "debit": discounted_sales, "credit": 0},
        {"date": "2025-6-12", "account": "Accounts Receivable", "debit": 0, "credit": discounted_sales},
    ],
    description="",
)

display(HTML(format_ledger_table(restin).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

---

##### **BE6.4 (LO 2) Roeher Company sold 9,000 of its specialty shelving to Elkins Office Supply Co. on account.**

**Prepare the entries when:**
- (a) Roeher makes the sale, 
- (b) Roeher grants an allowance of 700 when some of the shelving does not meet exact specifications but still could be sold by Elkins, and 
- (c) at year-end; Roeher estimates that an additional 200 in allowances will be granted to Elkins.

In [13]:
roeher = Ledger()
roeher.reset()

sales = 9000
allowance = 700
additional_allowance = 200

roeher.add_entry(
    [
        {"date": "2025-6-1", "account": "Accounts Receivable", "debit": sales, "credit": 0},
        {"date": "2025-6-1", "account": "Sales Revenue", "debit": 0, "credit": sales},
    ],
    description="To record sale of shelving to Elkins",
)

roeher.add_entry(
    [
        {"date": "2025-6-15", "account": "Sales Returns and Allowances", "debit": allowance, "credit": 0},
        {"date": "2025-6-15", "account": "Accounts Receivable", "debit": 0, "credit": allowance},
    ],
    description="To grant allowance to Elkins for a specification defect.",
)

roeher.add_entry(
    [
        {"date": "2025-12-31", "account": "Sales Returns and Allowances", "debit": additional_allowance, "credit": 0},
        {"date": "2025-12-31", "account": "Allowance for Sales Returns and Allowances", "debit": 0, "credit": additional_allowance},
    ],
    description="To record estimated allowances for Elkins.",
)
display(HTML(format_ledger_table(roeher).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1 — To record sale of shelving to Elkins
Saved transaction id 2 — To grant allowance to Elkins for a specification defect.
Saved transaction id 3 — To record estimated allowances for Elkins.

---

##### **BE6.5 (LO 3) Wilton, Inc. had net sales in 2025 of 1,400,000. At December 31, 2025, before adjusting entries, the balances in selected accounts were Accounts Receivable 250,000 debit, and Allowance for Doubtful Accounts 2,400 credit. If Wilton estimates that 8% of its receivables will prove to be uncollectible, prepare the December 31, 2025, journal entry to record bad debt expense.**

In [22]:
probability = .08
accounts_receivable = 250000 
allowance_for_doubtful_accounts = -2400 # Credit
estimated_allowance = accounts_receivable * probability
print(f"The estimated Allowance for Doubtful Account is: $ {estimated_allowance:,.0f}\n")
bad_debt_expense = estimated_allowance + allowance_for_doubtful_accounts

wilton = Ledger()
wilton.reset()

wilton.add_entry(
    [
        {"date": "2025-12-31", "account": "Bad Debt Expense", "debit": bad_debt_expense, "credit": 0},
        {"date": "2025-12-31", "account": "Allowance for Doubtful Accounts", "debit": 0, "credit": bad_debt_expense},
    ],
    description="To record bad debt expense for the year.",
)
display(HTML(format_ledger_table(wilton).to_html(index=False)))

The estimated Allowance for Doubtful Account is: $ 20,000

Ledger has been reset.
Saved transaction id 1 — To record bad debt expense for the year.

---

##### **BE6.6 (LO 3) Use the information presented in BE6.5 for Wilton, Inc.**

- **a. Instead of an Allowance for Doubtful Accounts Balance of 2,400 credit, the balance was 1,900 debit. Assume that 10% of accounts receivable will prove to be uncollectible. Prepare the entry to record bad debt expense.**

In [14]:
probability = .10
accounts_receivable = 250000 
allowance_for_doubtful_accounts = 1900 # Debit
estimated_allowance = accounts_receivable * probability
print(f"The estimated Allowance for Doubtful Account is: $ {estimated_allowance:,.0f}\n")
bad_debt_expense = estimated_allowance + allowance_for_doubtful_accounts

wilton = Ledger()
wilton.reset()

wilton.add_entry(
    [
        {"date": "2025-12-31", "account": "Bad Debt Expense", "debit": bad_debt_expense, "credit": 0},
        {"date": "2025-12-31", "account": "Allowance for Doubtful Accounts", "debit": 0, "credit": bad_debt_expense},
    ],
    description="To record bad debt expense for the year.",
)
display(HTML(format_ledger_table(wilton).to_html(index=False)))

The estimated Allowance for Doubtful Account is: $ 25,000

Ledger has been reset.
Saved transaction id 1 — To record bad debt expense for the year.

- **b. Instead of estimating uncollectibles based on a percentage of receivables, assume Wilton prepares an aging schedule that estimates total uncollectible accounts at 24,600. (Assume an allowance of 2,400 credit.) Prepare the entry to record bad debt expense.**

In [20]:
allowance_for_doubtful_accounts = -2400 # credit
estimated_allowance = 24600
print(f"The estimated Allowance for Doubtful Account is: $ {estimated_allowance:,.0f}\n")
bad_debt_expense = estimated_allowance + allowance_for_doubtful_accounts

wilton = Ledger()
wilton.reset()

wilton.add_entry(
    [
        {"date": "2025-12-31", "account": "Bad Debt Expense", "debit": bad_debt_expense, "credit": 0},
        {"date": "2025-12-31", "account": "Allowance for Doubtful Accounts", "debit": 0, "credit": bad_debt_expense},
    ],
    description="To record bad debt expense for the year.",
)
display(HTML(format_ledger_table(wilton).to_html(index=False)))

The estimated Allowance for Doubtful Account is: $ 24,600

Ledger has been reset.
Saved transaction id 1 — To record bad debt expense for the year.

---

##### **BE6.7 (LO 4) Milner Family Importers sold goods to Tung Decorators for 30,000 on November 1, 2025, accepting Tung’s 30,000, 6-month, 6% note. Prepare Milner’s November 1 entry, December 31 annual adjusting entry, and May 1 entry for the collection of the note and interest.**

In [19]:
note = 30000
stated_rate = .06
periods = 6
interest = note * (stated_rate * (6/12))

milner = Ledger()
milner.reset()

milner.add_entry(
    [
        {"date": "2025-11-1", "account": "Notes Receivable", "debit": note, "credit": 0},
        {"date": "2025-11-1", "account": "Sales Revenue", "debit": 0, "credit": note},
    ],
    description="",
)

interest_for_the_year = interest * (2 / 6)

milner.add_entry(
    [
        {"date": "2025-12-31", "account": "Interest Receivable", "debit": interest_for_the_year, "credit": 0},
        {"date": "2025-12-31", "account": "Interest Revenue", "debit": 0, "credit": interest_for_the_year},
    ],
    description="",
)
cash = note + interest
interest_revenue = interest * (4 / 6)
milner.add_entry(
    [
        {"date": "2026-5-1", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2026-5-1", "account": "Notes Receivable", "debit": 0, "credit": note},
        {"date": "2026-5-1", "account": "Interest Receivable", "debit": 0, "credit": interest_for_the_year},
        {"date": "2026-5-1", "account": "Interest Revenue", "debit": 0, "credit": interest_revenue},
    ],
    description="",
)

display(HTML(format_ledger_table(milner).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3

---

##### **BE6.8 (LO 4) Dold Acrobats lent 16,529 to Donaldson, Inc., accepting Donaldson’s 2-year, 20,000, zero-interest-bearing note. The implied interest rate is 10%. Prepare Dold’s journal entries for the initial transaction, recognition of interest each year, and the collection of 20,000 at maturity.**

In [22]:
note = 20000
cash_paid = 16529
interest = note - cash_paid
periodic_interest = interest * (1 / 2)

In [24]:
dold = Ledger()
dold.reset()

dold.add_entry(
    [
        {"date": "2025-1-1", "account": "Notes Receivable", "debit": note, "credit": 0},
        {"date": "2025-1-1", "account": "Discount on Notes Receivable", "debit": 0, "credit": interest},
        {"date": "2025-1-1", "account": "Cash", "debit": 0, "credit": cash_paid},
    ],
    description="",
)

dold.add_entry(
    [
        {"date": "2025-12-31", "account": "Discount on Notes Receivable", "debit": periodic_interest, "credit": 0},
        {"date": "2025-12-31", "account": "Interest Revenue", "debit": 0, "credit": periodic_interest},
    ],
    description="",
)

dold.add_entry(
    [
        {"date": "2026-12-31", "account": "Discount on Notes Receivable", "debit": periodic_interest, "credit": 0},
        {"date": "2026-12-31", "account": "Interest Revenue", "debit": 0, "credit": periodic_interest},
    ],
    description="",
)

dold.add_entry(
    [
        {"date": "2027-1-1", "account": "Cash", "debit": note, "credit": 0},
        {"date": "2027-1-1", "account": "Notes Receivable", "debit": 0, "credit": note},
    ],
    description="",
)

display(HTML(format_ledger_table(dold).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3
Saved transaction id 4

---

##### **BE6.9 (LO 5) On October 1, 2025, Chung, Inc. assigns 1,000,000 of its accounts receivable to Seneca National Bank as collateral for a 750,000 note. The bank assesses a finance charge of 2% of the receivables assigned and interest on the note of 9%. Prepare the October 1 journal entries for both Chung and Seneca.**

In [26]:
note = 750000
collateral = 1000000
finance_charge = collateral * .02
cash = note - finance_charge

**Chung, Inc.**

In [ ]:
chung = Ledger()
chung.reset()

chung.add_entry(
    [
        {"date": "2025-10-1", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2025-10-1", "account": "Interest Expense", "debit": finance_charge, "credit": 0},
        {"date": "2025-10-1", "account": "Notes Payable", "debit": 0, "credit": note},
    ],
    description="",
)

display(HTML(format_ledger_table(chung).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1

**Seneca National Bank**

In [29]:
seneca = Ledger()
seneca.reset()

seneca.add_entry(
    [
        {"date": "2025-10-1", "account": "Notes Receivable", "debit": note, "credit": 0},
        {"date": "2025-10-1", "account": "Interest Revenue", "debit": 0, "credit": finance_charge},
        {"date": "2025-10-1", "account": "cash", "debit": 0, "credit": cash},
    ],
    description="",
)

display(HTML(format_ledger_table(seneca).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1

---

##### **BE6.10 (LO 5) Wood Incorporated factored 150,000 of accounts receivable with Engram Factors Inc. on a without-recourse basis. Engram assesses a 2% finance charge of the amount of accounts receivable and retains an amount equal to 6% of accounts receivable for possible adjustments. Prepare the journal entry for Wood Incorporated and Engram Factors to record the factoring of the accounts receivable to Engram.**

In [52]:
finance_charge_pct = .02
retainer_pct = .06
accounts_receivable = 150000

retainer = accounts_receivable * retainer_pct
finance_charge = accounts_receivable * finance_charge_pct

cash = f'{accounts_receivable} {retainer} - {finance_charge} -'
cash = RPNEngine(cash).safe_evaluate().value

**Wood Incorporated**

In [55]:
wood = Ledger()
wood.reset()

wood.add_entry(
    [
        {"date": "2025-1-1", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2025-1-1", "account": "Receivable from Factor (Engram)", "debit": retainer, "credit": 0},
        {"date": "2025-1-1", "account": "Loss on Sale of Receivables", "debit": finance_charge, "credit": 0},
        {"date": "2025-1-1", "account": "Accounts Receivables", "debit": 0, "credit": accounts_receivable},
    ],
    description="",
)

display(HTML(format_ledger_table(wood).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1

**Engram Factors**

In [54]:
engram = Ledger()
engram.reset()

engram.add_entry(
    [
        {"date": "2025-1-1", "account": "Accounts Receivable", "debit": accounts_receivable, "credit": 0},
        {"date": "2025-1-1", "account": "Due to Customer (Wood)", "debit": 0, "credit": retainer},
        {"date": "2025-1-1", "account": "Interest Revenue", "debit": 0, "credit": finance_charge},
        {"date": "2025-1-1", "account": "Cash", "debit": 0, "credit": cash},
    ],
    description="",
)

display(HTML(format_ledger_table(engram).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1

---

##### **BE6.11 (LO 5) Use the information in BE6.10 for Wood. Assume that the receivables are sold with recourse. Prepare the journal entry for Wood to record the sale, assuming that the recourse liability has a fair value of 7,500.**

In [56]:
wood = Ledger()
wood.reset()

recourse_liability = 7500
loss_on_sale = f'{accounts_receivable} {cash} {retainer} + {recourse_liability} - -'
loss_on_sale = RPNEngine(loss_on_sale).safe_evaluate().value

wood.add_entry(
    [
        {"date": "2025-1-1", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2025-1-1", "account": "Receivable from Seneca", "debit": retainer, "credit": 0},
        {"date": "2025-1-1", "account": "Loss on Sale of Receivables", "debit": loss_on_sale, "credit": 0},
        {"date": "2025-1-1", "account": "Accounts Receivables", "debit": 0, "credit": accounts_receivable},
        {"date": "2025-1-1", "account": "Recourse Liability", "debit": 0, "credit": recourse_liability},
    ],
    description="",
)

display(HTML(format_ledger_table(wood).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1

---

##### **BE6.12 (LO 5) Arness Woodcrafters sells 250,000 of receivables to Commercial Factors, Inc. on a with recourse basis. Commercial assesses a finance charge of 5% and retains an amount equal to 4% of accounts receivable. Arness estimates the fair value of the recourse liability to be 8,000. Prepare the journal entry for Arness to record the sale.**

In [49]:
arness = Ledger()
arness.reset()

finance_charge_pct = .05
retainer_pct = .04
accounts_receivable = 250000

retainer = accounts_receivable * retainer_pct
finance_charge = accounts_receivable * finance_charge_pct

cash = f'{accounts_receivable} {retainer} - {finance_charge} -'
cash = RPNEngine(cash).safe_evaluate().value

recourse_liability = 8000
loss_on_sale = f'{accounts_receivable} {cash} {retainer} + {recourse_liability} - -'
loss_on_sale = RPNEngine(loss_on_sale).safe_evaluate().value

arness.add_entry(
    [
        {"date": "2025-1-1", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2025-1-1", "account": "Receivable from Seneca", "debit": retainer, "credit": 0},
        {"date": "2025-1-1", "account": "Loss on Sale of Receivables", "debit": loss_on_sale, "credit": 0},
        {"date": "2025-1-1", "account": "Accounts Receivables", "debit": 0, "credit": accounts_receivable},
        {"date": "2025-1-1", "account": "Recourse Liability", "debit": 0, "credit": recourse_liability},
    ],
    description="",
)

display(HTML(format_ledger_table(arness).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1

---

##### **BE6.13 (LO 5) Use the information presented in BE6.12 for Arness Woodcrafters but assume that the recourse liability has a fair value of 4,000, instead of 8,000. Prepare the journal entry and discuss the effects of this change in the value of the recourse liability on Arness’s financial statements.**

In [50]:
arness = Ledger()
arness.reset()

recourse_liability = 4000
loss_on_sale = f'{accounts_receivable} {cash} {retainer} + {recourse_liability} - -'
loss_on_sale = RPNEngine(loss_on_sale).safe_evaluate().value

arness.add_entry(
    [
        {"date": "2025-1-1", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2025-1-1", "account": "Receivable from Seneca", "debit": retainer, "credit": 0},
        {"date": "2025-1-1", "account": "Loss on Sale of Receivables", "debit": loss_on_sale, "credit": 0},
        {"date": "2025-1-1", "account": "Accounts Receivables", "debit": 0, "credit": accounts_receivable},
        {"date": "2025-1-1", "account": "Recourse Liability", "debit": 0, "credit": recourse_liability},
    ],
    description="",
)

display(HTML(format_ledger_table(arness).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1

---