# The Accounting Information System

**Selected Brief Excercises**

Intermediate Accounting 18th Edition

Kieso, Weygant, Warfield

In [1]:
import os
import sys
import pandas as pd
from datetime import date
from IPython.display import display, HTML

mod_path = os.path.abspath(os.path.join(".."))
if mod_path not in sys.path:
    sys.path.append(mod_path)

from ledger import Ledger

def months_elapsed(payment_date: date, entry_date: date) -> int:
    """Used to get the number of months elapsed"""
    return (entry_date.year - payment_date.year) * 12 + (entry_date.month - payment_date.month) + 1

---

##### **BE2.1 (LO 2) Transactions for Mehta Company for the month of May are presented below. Prepare journal entries for each of these transactions. (You may omit explanations.)**

- **May 1 - B.D. Mehta invests 4,000 cash in exchange for common stock in a small welding corporation.**
- **May 3 - Buys equipment on account for 1,100.**
- **May 13 - Pays 400 to landlord for May rent.**
- **May 21 - Bills Noble Corp. 500 for welding work done.**

In [2]:
ledger = Ledger()
ledger.reset()

may_1 = ledger.add_entry(
    [
        {"date": "2024-05-01", "account": "Cash", "debit": 4000, "credit": 0},
        {"date": "2024-05-01", "account": "Common Stock", "debit": 0, "credit": 4000},
    ],
    description="",
)

may_3 = ledger.add_entry(
    [
        {"date": "2024-05-03", "account": "Equipment", "debit": 1100, "credit": 0},
        {"date": "2024-05-03", "account": "Accounts Payable", "debit": 0, "credit": 1100},
    ],
    description="",
)

may_13 = ledger.add_entry(
    [
        {"date": "2024-05-13", "account": "Rent Expense", "debit": 400, "credit": 0},
        {"date": "2024-05-13", "account": "Cash", "debit": 0, "credit": 400},
    ],
    description="",
)

may_21 = ledger.add_entry(
    [
        {"date": "2024-05-21", "account": "Accounts Receivable", "debit": 500, "credit": 0},
        {"date": "2024-05-21", "account": "Revenue", "debit": 0, "credit": 500},
    ],
    description="",
)

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3
Saved transaction id 4

In [3]:
entries = ledger.to_table()
entries["debit"] = entries["debit"].apply(lambda x: f"{x:,.2f}")
entries["credit"] = entries["credit"].apply(lambda x: f"{x:,.2f}")
display(HTML(entries.to_html(index=False)))

---

##### **BE2.2 (LO 2) Agazzi Repair Shop had the following transactions during the first month of business as a proprietorship. Journalize the transactions. (Omit explanations.)**

- **Aug 2 - Invested 12,000 cash and 2,500 of equipment in the business.**
- **Aug 7 - Purchased supplies on account for 500. (Debit asset account.)**
- **Aug 12 - Performed services for clients, for which 1,300 was collected in cash and 670 was billed to the clients.**
- **Aug 15 - Paid August rent 600.**
- **Aug 19 - Counted supplies and determined that only 270 of the supplies purchased on August 7 are still on hand.**

In [4]:
agazzi = Ledger()
agazzi.reset()

cash = 12000
equipment = 2500
investment = cash + equipment

aug_2 = agazzi.add_entry(
    [
        {"date": "2025-8-2", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2025-8-2", "account": "Equipment", "debit": equipment, "credit": 0},
        {"date": "2025-8-2", "account": "Owner's Capital", "debit": 0, "credit": investment},
    ],
    description="",
)

supplies_purchased = 500

aug_7 = agazzi.add_entry(
    [
        {"date": "2025-8-7", "account": "Supplies", "debit": supplies_purchased, "credit": 0},
        {"date": "2025-8-7", "account": "Accounts Payable", "debit": 0, "credit": supplies_purchased},
    ],
    description="",
)

cash = 1300
ar = 670
revenue = cash + ar

aug_12 = agazzi.add_entry(
    [
        {"date": "2025-8-12", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2025-8-12", "account": "Accounts Receivable", "debit": ar, "credit": 0},
        {"date": "2025-8-12", "account": "Service Revenue", "debit": 0, "credit": revenue},
    ],
    description="",
)
aug_15 = agazzi.add_entry(
    [
        {"date": "2025-8-15", "account": "Rent Expense", "debit": 600, "credit": 0},
        {"date": "2025-8-15", "account": "Cash", "debit": 0, "credit": 600},
    ],
    description="",
)

supplies_on_hand = 270
supplies_expense = supplies_purchased - supplies_on_hand

aug_19 = agazzi.add_entry(
    [
        {"date": "2025-8-19", "account": "Supplies Expense", "debit": supplies_expense, "credit": 0},
        {"date": "2025-8-19", "account": "Supplies", "debit": 0, "credit": supplies_expense},
    ],
    description="",
)

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3
Saved transaction id 4
Saved transaction id 5

In [5]:
entries = agazzi.to_table()
entries["debit"] = entries["debit"].apply(lambda x: f"{x:,.2f}")
entries["credit"] = entries["credit"].apply(lambda x: f"{x:,.2f}")
display(HTML(entries.to_html(index=False)))

---

##### **BE2.3 (LO 2, 3) On July 1, 2025, Crowe Co. pays 15,000 to Zubin Insurance Co. for a 3-year insurance policy. Both companies have fiscal years ending December 31. For Crowe Co., journalize the entry on July 1 and the adjusting entry on December 31.**

In [6]:
crowe = Ledger()
crowe.reset()

insurance = 15000
expense_per_year = insurance / 3

jul_1 = crowe.add_entry(
    [
        {"date": "2025-7-2", "account": "Pre-Paid Insurance", "debit": insurance, "credit": 0},
        {"date": "2025-7-2", "account": "Cash", "debit": 0, "credit": insurance},
    ],
    description="",
)

payment_date = date(2025, 7, 1)
adjusting_date = date(2025, 12, 31)
months = months_elapsed(payment_date, adjusting_date)
insurance_expense = (expense_per_year / 12) * months

dec_31 = crowe.add_entry(
    [
        {"date": "2025-12-31", "account": "Insurance Expense", "debit": insurance_expense, "credit": 0},
        {"date": "2025-12-31", "account": "Pre-Paid Insurance", "debit": 0, "credit": insurance_expense},
    ],
    description="",
)

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

In [7]:
entries = crowe.to_table()
entries["debit"] = entries["debit"].apply(lambda x: f"{x:,.2f}")
entries["credit"] = entries["credit"].apply(lambda x: f"{x:,.2f}")
display(HTML(entries.to_html(index=False)))

---

##### **BE2.4 (LO 2, 3) Using the data in BE2.3, journalize the entry on July 1 and the adjusting entry on December 31 for Zubin Insurance Co. Zubin uses the accounts Unearned Service Revenue and Service Revenue.**

In [14]:
zubin = Ledger()
zubin.reset()

insurance = 15000
revenue_per_year = insurance / 3

jul_1 = zubin.add_entry(
    [
        {"date": "2025-7-2", "account": "Cash", "debit": insurance, "credit": 0},
        {"date": "2025-7-2", "account": "Unearned Service Revenue", "debit": 0, "credit": insurance},
    ],
    description="",
)

payment_date = date(2025, 7, 1)
adjusting_date = date(2025, 12, 31)
months = months_elapsed(payment_date, adjusting_date)
insurance_revenue = (revenue_per_year / 12) * months

dec_31 = zubin.add_entry(
    [
        {"date": "2025-12-31", "account": "Unearned Service Revenue", "debit": insurance_revenue, "credit": 0},
        {"date": "2025-12-31", "account": "Service Revenue", "debit": 0, "credit": insurance_revenue},
    ],
    description="",
)

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

In [15]:
entries = zubin.to_table()
entries["debit"] = entries["debit"].apply(lambda x: f"{x:,.2f}")
entries["credit"] = entries["credit"].apply(lambda x: f"{x:,.2f}")
display(HTML(entries.to_html(index=False)))

---

##### **BE2.5 (LO 2, 3) Assume that on February 1, Procter & Gamble (P&G) paid 720,000 in advance for 2 years’ insurance coverage. Prepare P&G’s February 1 journal entry and the annual adjusting entry on June 30.**

In [10]:
insurance = 720000
insurance_per_month = insurance / 24
payment_date = date(2025, 2, 1)
adjusting_date = date(2025, 6, 30)
months = months_elapsed(payment_date, adjusting_date)
insurance_expense = insurance_per_month * months

png = Ledger()
png.reset()

# February 1, 2025
feb_2 = png.add_entry(
    [
        {"date": "2025-2-1", "account": "Pre-paid Insurance", "debit": insurance, "credit": 0},
        {"date": "2025-2-1", "account": "Cash", "debit": 0, "credit": insurance},
    ],
    description="",
)

# June 30, 2025
june_30 = png.add_entry(
    [
        {"date": "2025-6-30", "account": "Insurance Expense", "debit": insurance_expense, "credit": 0},
        {"date": "2025-6-30", "account": "Pre-Paid Insurance", "debit": 0, "credit": insurance_expense},
    ],
    description="",
)

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

In [11]:
entries = png.to_table()
entries["debit"] = entries["debit"].apply(lambda x: f"{x:,.2f}")
entries["credit"] = entries["credit"].apply(lambda x: f"{x:,.2f}")
display(HTML(entries.to_html(index=False)))

---

##### **BE2.6 (LO 2, 3) LaBouche Corporation owns a warehouse. On November 1, it rented storage space to a lessee (tenant) for 3 months for a total cash payment of 2,400 received in advance. Prepare LaBouche’s November 1 journal entry and the December 31 annual adjusting entry.**

In [12]:
laBouche = Ledger()
laBouche.reset()

payment = 2400
payment_per_month = payment / 3
payment_date = date(2025, 11, 1)
adjusting_date = date(2025, 12, 31)
months = months_elapsed(payment_date, adjusting_date)
revenue = payment_per_month * months

# November 1, 2025
nov_1 = laBouche.add_entry(
    [
        {"date": "2025-11-1", "account": "Cash", "debit": payment, "credit": 0},
        {"date": "2025-11-1", "account": "Unearned Revenue", "debit": 0, "credit": payment},
    ],
    description="",
)

# December 31, 2025
dec_30 = laBouche.add_entry(
    [
        {"date": "2025-12-31", "account": "Unearned Revenue", "debit": revenue, "credit": 0},
        {"date": "2025-12-31", "account": "Rent Revenue", "debit": 0, "credit": revenue},
    ],
    description="",
)

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2

In [13]:
entries = laBouche.to_table()
entries["debit"] = entries["debit"].apply(lambda x: f"{x:,.2f}")
entries["credit"] = entries["credit"].apply(lambda x: f"{x:,.2f}")
display(HTML(entries.to_html(index=False)))

---