# The Accounting Information System

**Selected Excercises**

Intermediate Accounting 18th Edition

Kieso, Weygant, Warfield

In [2]:
import os
import sys
import pandas as pd
from datetime import date
from IPython.display import display, HTML

mod_path = os.path.abspath(os.path.join(".."))
if mod_path not in sys.path:
    sys.path.append(mod_path)

from ledger import Ledger, TrialBalance
from helpers import format_ledger_table, format_trial_balance_table, asset_amortization, format_amortization_table

---

##### **E2.1 (LO 2) (Transaction Analysis—­Service Company) Beverly Crusher is a licensed CPA. During the first month of operations of her business (a sole proprietorship), the following events and transactions occurred.**

- **April 2** -  Invested 32,000 cash and equipment valued at 14,000 in the business.
- **April 2** - Hired an administrative assistant at a salary of 290 per week payable monthly.
- **April 3** - Purchased supplies on account 700. (Debit an asset account.)
- **April 7** - Paid office rent of 600 for the month.
- **April 11** - Completed a tax assignment and billed client 1,100 for services rendered. (Use Service Revenue account.)
- **April 12** - Received 3,200 advance on a management consulting engagement.
- **April 17** - Received cash of 2,300 for services completed for Ferengi Co.
- **April 21** - Paid insurance expense 110.
- **April 30** - Paid administrative assistant 1,160 for the month.
- **April 30** - A count of supplies indicated that 120 of supplies had been used.
- **April 30** - Purchased a new computer for 6,100 with personal funds. (The computer will be used exclusively for business purposes.)

##### **Instructions**

Journalize the transactions in the general journal. (Omit explanations.)

In [2]:
beverly = Ledger()
beverly.reset()

cash = 32000
equipment = 14000
investment = cash + equipment
apr_2 = beverly.add_entry(
    [
        {"date": "2026-4-2", "account": "Cash", "debit": cash, "credit": 0},
        {"date": "2026-4-2", "account": "Equipment", "debit": equipment, "credit": 0},
        {"date": "2026-4-2", "account": "Owner's Equity", "debit": 0, "credit": investment},
    ],
    description="",
)

supplies = 700
apr_3 = beverly.add_entry(
    [
        {"date": "2026-4-3", "account": "Supplies", "debit": supplies, "credit": 0},
        {"date": "2026-4-3", "account": "Accounts Payable", "debit": 0, "credit": supplies},
    ],
    description="",
)

rent = 600
apr_7 = beverly.add_entry(
    [
        {"date": "2026-4-7", "account": "Rent Expense", "debit": rent, "credit": 0},
        {"date": "2026-4-7", "account": "Cash", "debit": 0, "credit": rent},
    ],
    description="",
)

services = 1100
apr_11 = beverly.add_entry(
    [
        {"date": "2026-4-11", "account": "Accounts Receivable", "debit": services, "credit": 0},
        {"date": "2026-4-11", "account": "Service Revenue", "debit": 0, "credit": services},
    ],
    description="",
)

advance = 3200
apr_12 = beverly.add_entry(
    [
        {"date": "2026-4-12", "account": "Cash", "debit": advance, "credit": 0},
        {"date": "2026-4-12", "account": "Unearned Revenue", "debit": 0, "credit": advance},
    ],
    description="",
)

services = 2300
apr_17 = beverly.add_entry(
    [
        {"date": "2026-4-17", "account": "Cash", "debit": services, "credit": 0},
        {"date": "2026-4-17", "account": "Service Revenue", "debit": 0, "credit": services},
    ],
    description="",
)

insurance = 110
apr_21 = beverly.add_entry(
    [
        {"date": "2026-4-21", "account": "Pre-Paid Insurance", "debit": insurance, "credit": 0},
        {"date": "2026-4-21", "account": "Cash", "debit": 0, "credit": insurance},
    ],
    description="",
)

wages = 1160
apr_30 = beverly.add_entry(
    [
        {"date": "2026-4-30", "account": "Wages Expense", "debit": wages, "credit": 0},
        {"date": "2026-4-30", "account": "Cash", "debit": 0, "credit": wages},
    ],
    description="",
)
supplies_used = 120
apr_30 = beverly.add_entry(
    [
        {"date": "2026-4-30", "account": "Supplies Expense", "debit": supplies_used, "credit": 0},
        {"date": "2026-4-30", "account": "Supplies", "debit": 0, "credit": supplies_used},
    ],
    description="",
)

computer = 6100
apr_30 = beverly.add_entry(
    [
        {"date": "2026-4-30", "account": "Equipment", "debit": computer, "credit": 0},
        {"date": "2026-4-30", "account": "Cash", "debit": 0, "credit": computer},
    ],
    description="",
)

display(HTML(format_ledger_table(beverly).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3
Saved transaction id 4
Saved transaction id 5
Saved transaction id 6
Saved transaction id 7
Saved transaction id 8
Saved transaction id 9
Saved transaction id 10

---

##### **E2.2 (LO 2) (Corrected Trial Balance) The following trial balance of Wanda Landowska Company does not balance. Your review of the ledger reveals the following.**

- (a) Each account had a normal balance. 
- (b) The debit footings in Prepaid Insurance, Accounts Payable, and Property Tax Expense were each understated 100. 
- (c) A transposition error was made in Accounts Receivable and Service Revenue; the correct balances for Accounts Receivable and Service Revenue are 2,750 and 6,690, respectively.
- (d) A debit posting to Advertising Expense of 300 was omitted. 
- (e) A 1,500 cash drawing by the owner was debited to Owner’s Capital and credited to Cash.


| Wanda Landowska Company |
| :---: |
| Trial Balance |
| April 30, 2025 |
| ----------------------------------------------------- |

| | Debit | Credit |
| --- | :---: | :---: |
| Cash | 4,800 | |
| Accounts Receivable | 2,570 | |
| Prepaid Insurance | 700 | |
| Equipment |  | 8,000 |
| Accounts Payable |  | 4,500 |
| Property Taxes Payable | 560 | 0 |
| Owner's Capital |  | 11,200 |
| Service Revenue | 6,960 |  |
| Salaries and Wages Expense | 4,200 |  |
| Advertising Expense | 1,100 |  |
| Property Tax Expense |  | 800 |
|  | **20,890** | **24,500** |

##### **Instruction**

Prepare a correct trial balance.

In [3]:
tb = TrialBalance()
tb.reset()
tb.add_account("Cash", debit=4800, account_type="asset")
tb.add_account("Accounts Receivable", debit=2570, account_type="asset")
tb.add_account("Prepaid Insurance", debit=700, account_type="asset")
tb.add_account("Equipment", debit=8000, account_type="asset")
tb.add_account("Accounts Payable", credit=4500, account_type="liability")
tb.add_account("Property Taxes Payable", credit=560, account_type="liability")
tb.add_account("Owner's Capital", credit=11200, account_type="equity")
tb.add_account("Service Revenue", credit=6960, account_type="revenue")
tb.add_account("Salaries and Wages Expense", debit=4200, account_type="expense")
tb.add_account("Advertising Expense", debit=1100, account_type="expense")
tb.add_account("Property Tax Expense", debit=800, account_type="expense")

Trial balance has been reset.

In [4]:
display(HTML(format_trial_balance_table(tb).to_html(index=False)))
print("Balanced:", tb.is_balanced())

Balanced: False

##### **Adjustments**

In [5]:
tb.adjust_account("Prepaid Insurance", debit_change=100)      # (b)
tb.adjust_account("Accounts Payable", credit_change=-100)     # (b)
tb.adjust_account("Property Tax Expense", debit_change=100)   # (b)
tb.adjust_account("Accounts Receivable", debit_change=180)    # (c)
tb.adjust_account("Service Revenue", credit_change=-270)      # (c)
tb.adjust_account("Advertising Expense", debit_change=300)    # (d)


je_corrections = Ledger()
je_corrections.add_entry(
    [
        {"date": "2025-04-30", "account": "Owner's Drawings", "debit": 1500, "credit": 0},
        {"date": "2025-04-30", "account": "Owner's Capital", "debit": 0, "credit": 1500}
    ],
    description="Reclassify $1,500 cash drawing from Owner's Capital to Owner's Drawings"
)

tb.apply_ledger(je_corrections, account_types={"Owner's Drawings": "equity"})

Saved transaction id 1 — Reclassify $1,500 cash drawing from Owner's Capital to Owner's Drawings

In [6]:
display(HTML(format_trial_balance_table(tb).to_html(index=False)))
print("Balanced:", tb.is_balanced())

Balanced: True

---

##### **E2.3 (LO 2) (Corrected Trial Balance) The following trial balance of Blues Traveler Corporation does not balance.**

| Blues Traveler Corporation |
| :---: |
| Trial Balance |
| April 30, 2025 |
| -------------------------------------------- |

| | Debit | Credit |
| --- | :---: | :---: |
| Cash | 5,912 | |
| Accounts Receivable | 5,240 | |
| Supplies | 2,967 | |
| Equipment | 6,100 | |
| Accounts Payable |  | 7,044 |
| Common Stock |  | 8,000 |
| Retained Earnings |  | 2,000 |
| Service Revenue |  | 5,200  |
| Office Expense | 4,320 |  |
|  | **24,539** | **22,244** |

An examination of the ledger shows these errors.

1. Cash received from a customer on account was recorded (both debit and credit) as 1,380 instead of 1,830.
2. The purchase on account of a computer costing 3,200 was recorded as a debit to Office Expense and a credit to Accounts Payable.
3. Services were performed on account for a client, 2,250, for which Accounts Receivable was debited 2,250 and Service Revenue was credited 225.
4. A payment of 95 for telephone charges was entered as a debit to Office Expense and a debit to Cash.
5. The Service Revenue account was totaled at 5,200 instead of 5,280.

##### **Instruction**

From this information prepare a corrected trial balance.

In [7]:
blue_tb = TrialBalance()
blue_tb.reset()
blue_tb.add_account("Cash", debit=5912, account_type="asset")
blue_tb.add_account("Accounts Receivable", debit=5240, account_type="asset")
blue_tb.add_account("Supplies", debit=2967, account_type="asset")
blue_tb.add_account("Equipment", debit=6100, account_type="asset")
blue_tb.add_account("Accounts Payable", credit=7044, account_type="liability")
blue_tb.add_account("Common Stock", credit=8000, account_type="equity")
blue_tb.add_account("Retained Earnings", credit=2000, account_type="equity")
blue_tb.add_account("Service Revenue", credit=5200, account_type="revenue")
blue_tb.add_account("Office Expense", debit=4320, account_type="expense")

Trial balance has been reset.

In [8]:
display(HTML(format_trial_balance_table(blue_tb).to_html(index=False)))
print("Balanced:", blue_tb.is_balanced())

Balanced: False

##### **Adjustments**

In [9]:
blue_ledger = Ledger()
blue_ledger.reset()

# Error 1
blue_ledger.add_entry(
    [
        {"date": "2025-04-30", "account": "Cash", "debit": 1830-1380, "credit": 0},
        {"date": "2025-04-30", "account": "Accounts Receivable", "debit": 0, "credit": 1830-1380}
    ],
    description="Error 1: Correction of erroneous journal entry"
)

# Error 2
blue_ledger.add_entry(
    [
        {"date": "2025-04-30", "account": "Equipment", "debit": 3200, "credit": 0},
        {"date": "2025-04-30", "account": "Office Expense", "debit": 0, "credit": 3200}
    ],
    description="Error 2: Reclassify equipment recorded as expense"
)
 
blue_tb.adjust_account("Service Revenue", credit_change=2250-225)     # Error 3
blue_tb.adjust_account("Cash", credit_change=95*2)                    # Error 4
blue_tb.adjust_account("Service Revenue", credit_change=5280-5200)    # Error 5

blue_tb.apply_ledger(blue_ledger)

Ledger has been reset.
Saved transaction id 1 — Error 1: Correction of erroneous journal entry
Saved transaction id 2 — Error 2: Reclassify equipment recorded as expense

In [10]:
display(HTML(format_trial_balance_table(blue_tb).to_html(index=False)))
print("Balanced:", blue_tb.is_balanced())

Balanced: True

---

##### **E2.4 (LO 2) (Corrected Trial Balance) The following trial balance of Watteau Co. does not balance.**

| Watteau Co. |
| :---: |
| Trial Balance |
| June 30, 2025 |
| ----------------------------------------------------- |

| | Debit | Credit |
| --- | :---: | :---: |
| Cash | | 2,870 |
| Accounts Receivable | 3,231 | |
| Supplies | 800 | |
| Equipment | 3,800 | |
| Accounts Payable |  | 2,666 |
| Unearned Revenue | 1,200 | |
| Common Stock |  | 6,000 |
| Retained Earnings |  | 3,000 |
| Service Revenue |  | 2,380  |
| Salaries and Wages Expense | 3,400 | |
| Office Expense | 940 |  |
|  | **13,371** | **16,916** |

Each of the listed accounts should have a normal balance per the general ledger. An examination of the ledger and journal reveals the following errors.

1. Cash received from a customer on account was debited for 570, and Accounts Receivable was credited for the same amount. The actual collection was for 750.
2. The purchase of a computer printer on account for 500 was recorded as a debit to Supplies for 500
and a credit to Accounts Payable for 500
3. Services were performed on account for a client for 890. Accounts Receivable was debited for 890 and Service Revenue was credited for 89.
4. A payment of 65 for telephone charges was recorded as a debit to Office Expense for 65 and a debit to Cash for 65.
5. When the Unearned Service Revenue account was reviewed, it was found that service revenue amounting to 325 was performed prior to June 30 (related to Unearned Service Revenue).
6. A debit posting to Salaries and Wages Expense of 670 was omitted.
7. A payment on account for 206 was credited to Cash for 206 and credited to Accounts Payable for 260.
8. A dividend of 575 was debited to Salaries and Wages Expense for 575 and credited to Cash for 575.

**Instruction**

Prepare a correct trial balance. (Note: It may be necessary to add one or more accounts to the trial balance.)

In [16]:
# First we'll construct the trial balance according to the account's normal balance.

watteau_tb = TrialBalance()
watteau_tb.reset()

watteau_tb.add_account("Cash", debit=2870, account_type="asset")
watteau_tb.add_account("Accounts Receivable", debit=3231, account_type="asset")
watteau_tb.add_account("Supplies", debit=800, account_type="asset")
watteau_tb.add_account("Equipment", debit=3800, account_type="asset")
watteau_tb.add_account("Accounts Payable", credit=2666, account_type="liability")
watteau_tb.add_account("Unearned Service Revenue", credit=1200, account_type="liability")
watteau_tb.add_account("Common Stock", credit=6000, account_type="equity")
watteau_tb.add_account("Retained Earnings", credit=3000, account_type="equity")
watteau_tb.add_account("Service Revenue", credit=2380, account_type="revenue")
watteau_tb.add_account("Salaries and Wages Expense", debit=3400, account_type="expense")
watteau_tb.add_account("Office Expense", debit=940, account_type="expense")

display(HTML(format_trial_balance_table(watteau_tb).to_html(index=False)))
print("Balanced:", watteau_tb.is_balanced())

Trial balance has been reset.

Balanced: False

##### **Adjustments**

In [17]:
watteau_ledger = Ledger()
watteau_ledger.reset()

# Error 1
watteau_ledger.add_entry(
    [
        {"date": "2025-06-30", "account": "Cash", "debit": 750-570, "credit": 0},
        {"date": "2025-06-30", "account": "Accounts Receivable", "debit": 0, "credit": 750-570}
    ],
    description=""
)

# Error 2
watteau_ledger.add_entry(
    [
        {"date": "2025-06-30", "account": "Equipment", "debit": 500, "credit": 0},
        {"date": "2025-06-30", "account": "Supplies", "debit": 0, "credit": 500}
    ],
    description=""
)

# Error 3
watteau_tb.adjust_account("Service Revenue", credit_change=890-89)

# Error 4
watteau_tb.adjust_account("Cash", credit_change=65*2)

# Error 5
watteau_ledger.add_entry(
    [
        {"date": "2025-06-30", "account": "Unearned Service Revenue", "debit": 325, "credit": 0},
        {"date": "2025-06-30", "account": "Service Revenue", "debit": 0, "credit": 325}
    ],
    description=""
)

# Error 6
watteau_tb.adjust_account("Salaries and Wages Expense", debit_change=670)

# Error 7
watteau_tb.adjust_account("Accounts Payable", debit_change=260+206)

# Error 8
watteau_ledger.add_entry(
    [
        {"date": "2025-06-30", "account": "Dividends", "debit": 575, "credit": 0},
        {"date": "2025-06-30", "account": "Salaries and Wages Expense", "debit": 0, "credit": 575}
    ],
    description=""
)

watteau_tb.apply_ledger(watteau_ledger, account_types={"Dividends": "equity"})

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3
Saved transaction id 4

In [18]:
display(HTML(format_trial_balance_table(watteau_tb).to_html(index=False)))
print("Balanced:", watteau_tb.is_balanced())

Balanced: True

---

##### **E2.5 (LO 3) Excel (Adjusting Entries) The ledger of Duggan Rental Agency on March 31 of the current year includes the following selected accounts before adjusting entries have been prepared.**

| | Debit | Credit |
| --- | :---: | :---: |
| Prepaid Insuance | 3,600 | |
| Supplies | 2,800 | |
| Equipment | 25,000 | |
| Accumulated Depreciation - Equipment | | 8,400 |
| Notes Payable | | 20,000 |
| Unearned Rent Revenue | | 9,300 |
| Rent Revenue | | 60,000 |
| Interest Expense | | |
| Salaries and Wages Expense | 14,000 | |

An analysis of the accounts shows the following.

1. The equipment depreciates 250 per month.
2. One-­third of the unearned rent was recognized as revenue during the quarter.
3. Interest of 500 is accrued on the notes payable.
4. Supplies on hand total 850.
5. Insurance expires at the rate of 300 per month.

##### Instructions

Prepare the adjusting entries at March 31, assuming that adjusting entries are made quarterly. Additional accounts are Depreciation Expense, Insurance Expense, Interest Payable, and Supplies Expense. (Omit explanations.)

In [6]:
duggan = Ledger()
duggan.reset()

depreciation = 250 * 3
duggan.add_entry(
    [
        {"date": "2026-3-31", "account": "Depreciation Expense", "debit": depreciation, "credit": 0},
        {"date": "2026-3-31", "account": "Accumulated Depreciation - Equipment", "debit": 0, "credit": depreciation},
    ],
    description="",
)

revenue = 9300 * (1/3)
duggan.add_entry(
    [
        {"date": "2026-3-31", "account": "Unearned Rent Revenue", "debit": revenue, "credit": 0},
        {"date": "2026-3-31", "account": "Rent Revenue", "debit": 0, "credit": revenue},
    ],
    description="",
)
interest_expense = 500
duggan.add_entry(
    [
        {"date": "2026-3-31", "account": "Interest Expense", "debit": interest_expense, "credit": 0},
        {"date": "2026-3-31", "account": "Interest Payable", "debit": 0, "credit": interest_expense},
    ],
    description="",
)

supplies_exp = 2800 - 850
duggan.add_entry(
    [
        {"date": "2026-3-31", "account": "Supplies Expense", "debit": supplies_exp, "credit": 0},
        {"date": "2026-3-31", "account": "Supplies", "debit": 0, "credit": supplies_exp},
    ],
    description="",
)

insurance_expense = 300 * 3
duggan.add_entry(
    [
        {"date": "2026-3-31", "account": "Insurance Expense", "debit": insurance_expense, "credit": 0},
        {"date": "2026-3-31", "account": "Prepaid Insurance", "debit": 0, "credit": insurance_expense},
    ],
    description="",
)

display(HTML(format_ledger_table(duggan).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3
Saved transaction id 4
Saved transaction id 5

---

##### **E2.6 (LO 3) (Adjusting Entries) Karen Weller, D.D.S., opened a dental practice on January 1, 2025. During the first month of operations, the following transactions occurred.**

1. Performed services for patients who had dental plan insurance. At January 31, 750 of such services was performed but not yet billed to the insurance companies.
2. Utility expenses incurred but not paid prior to January 31 totaled 520.
3. Purchased dental equipment on January 1 for 80,000, paying 20,000 in cash and signing a 60,000,
3-year note payable. The equipment depreciates 400 per month. Interest is 500 per month.
4. Purchased a one-­year malpractice insurance policy on January 1 for 12,000.
5. Purchased 1,600 of dental supplies. On January 31, determined that 500 of supplies were on hand.

##### **Instructions**

Prepare the adjusting entries on January 31. (Omit explanations.) Account titles are Accumulated Depreciation—­Equipment, Depreciation Expense, Service Revenue, Accounts Receivable, Insurance Expense, Interest Expense, Interest Payable, Prepaid Insurance, Supplies, Supplies Expense, Utilities Expenses, and Accounts Payable.

In [12]:
weller = Ledger()
weller.reset()

weller.add_entry(
    [
        {"date": "2026-1-31", "account": "Accounts Receivable", "debit": 750, "credit": 0},
        {"date": "2026-1-31", "account": "Service Revenue", "debit": 0, "credit": 750},
    ],
    description="",
)

weller.add_entry(
    [
        {"date": "2026-1-31", "account": "Utilities Expenses", "debit": 520, "credit": 0},
        {"date": "2026-1-31", "account": "Accounts Payable", "debit": 0, "credit": 520},
    ],
    description="",
)

weller.add_entry(
    [
        {"date": "2026-1-31", "account": "Depreciation Expense", "debit": 400, "credit": 0},
        {"date": "2026-1-31", "account": "Accumulated Depreciation - Equipment", "debit": 0, "credit": 400},
    ],
    description="",
)

weller.add_entry(
    [
        {"date": "2026-1-31", "account": "Interest Expense", "debit": 500, "credit": 0},
        {"date": "2026-1-31", "account": "Interest Payable", "debit": 0, "credit": 500},
    ],
    description="",
)

insurance_exp = round(12000 / 12, 0)
weller.add_entry(
    [
        {"date": "2026-1-31", "account": "Insurance Expense", "debit": insurance_exp, "credit": 0},
        {"date": "2026-1-31", "account": "Prepaid Insurance", "debit": 0, "credit": insurance_exp},
    ],
    description="",
)

supplies_used = supplies - 500
weller.add_entry(
    [
        {"date": "2026-1-31", "account": "Supplies Expense", "debit": supplies_used, "credit": 0},
        {"date": "2026-1-31", "account": "Supplies", "debit": 0, "credit": supplies_used},
    ],
    description="",
)

display(HTML(format_ledger_table(weller).to_html(index=False)))

Ledger has been reset.
Saved transaction id 1
Saved transaction id 2
Saved transaction id 3
Saved transaction id 4
Saved transaction id 5
Saved transaction id 6

---

##### **E2.7 (LO 3) (Analyze Adjusted Data) A partial adjusted trial balance of Piper Company at January 31, 2025, shows the following.**

| Piper Company |
| :---: |
| Adjusted Trial Balance |
| January 31, 2025 |
| ----------------------------------------------------- |

| | Debit | Credit |
| --- | :---: | :---: |
| Supplies | 700 | |
| Prepaid Insurance | 2,400 | |
| Salaries and Wages Payable | | 800 |
| Unearned Service Revenue | | 750 |
| Supplies Expense | 950 | |
| Insurance Expense | 400 | |
| Salaries and Wages Expense | 1,800 | |
| Service Revenue | | 2,000 |

##### **Instructions**

Answer the following questions, assuming the year begins January 1.

- a. If the amount in Supplies Expense is the January 31 adjusting entry, and 850 of supplies was purchased in January, what was the balance in Supplies on January 1?

In [30]:
supplies_used = 950
supplies_purchased = 850
ending_balance = 700

beginning_balance = ending_balance + supplies_used - supplies_purchased

print(f"The beginning balance in the supplies account at January 1, was $ {beginning_balance:,.0f}\n")

print(f"{" "*16:<20} | {"Debit":>6} | {"Credit":>6} |")
print(f"{"-"*20:<20} | {"-"*6:>6} | {"-"*6:>6} |")
print(f"{"Beginning balance":<20} | {beginning_balance:>6,.0f} | {" "*6:>6} |")
print(f"{"Supplies purchased":<20} | {supplies_purchased:>6,.0f} | {" "*6:>6} |")
print(f"{"Supplies expense":<20} | {" "*6:>6} | {supplies_used:>6,.0f} |")
print(f"{"-"*20:<20} | {"-"*6:>6} | {"-"*6:>6} |")
print(f"{"Ending balance":<20} | {ending_balance:>6,.0f} | {" "*6:>6} |")
print(f"{"-"*20:<20} | {"-"*6:>6} | {"-"*6:>6} |")

The beginning balance in the supplies account at January 1, was $ 800

                     |  Debit | Credit |
-------------------- | ------ | ------ |
Beginning balance    |    800 |        |
Supplies purchased   |    850 |        |
Supplies expense     |        |    950 |
-------------------- | ------ | ------ |
Ending balance       |    700 |        |
-------------------- | ------ | ------ |

- b. If the amount in Insurance Expense is the January 31 adjusting entry, and the original insurance premium was for one year, what was the total premium and when was the policy purchased?

In [46]:
insurance_expense = 400
prepaid_insurance_beg_balance = insurance_expense * 12
prepaid_insurance_end_balance = 2400
expensed_insurance = prepaid_insurance_beg_balance - prepaid_insurance_end_balance
months = expensed_insurance / insurance_expense
print(f"The policy was purchased {months:.0f} months ago, on August of the previous year.")

The policy was purchased 6 months ago, on August of the previous year.

In [4]:

df = asset_amortization("2024-08-01", 12, 4800, "ME")
display(HTML(format_amortization_table(df).to_html(index=False)))

- c. If 2,500 of salaries was paid in January, what was the balance in Salaries and Wages Payable at December 31, 2024?

In [15]:
wages_paid = 2500
wages_expense = 1800
ending_balance = 800
beginning_balance =  ending_balance - wages_expense + wages_paid

print(f"The balance of the Salaries and Wages Payable account at December 31, was $ {beginning_balance:,.0f}\n")

print(f"{" "*16:<30} | {"Debit":>6} | {"Credit":>6} |")
print(f"{"-"*30:<30} | {"-"*6:>6} | {"-"*6:>6} |")
print(f"{"Beginning balance":<30} | {" "*6:>6} | {beginning_balance:>6,.0f} |")
print(f"{"Salaries and Wages Expense":<30} | {wages_expense:>6,.0f} | {" "*6:>6} |")
print(f"{"Salaries and Wages Paid":<30} | {wages_paid:>6,.0f} | {" "*6:>6} |")
print(f"{"-"*30:<30} | {"-"*6:>6} | {"-"*6:>6} |")
print(f"{"Ending balance":<30} | {" "*6:>6} | {ending_balance:>6,.0f} |")
print(f"{"-"*30:<30} | {"-"*6:>6} | {"-"*6:>6} |")

The balance of the Salaries and Wages Payable account at December 31, was $ 1,500

                               |  Debit | Credit |
------------------------------ | ------ | ------ |
Beginning balance              |        |  1,500 |
Salaries and Wages Expense     |  1,800 |        |
Salaries and Wages Paid        |  2,500 |        |
------------------------------ | ------ | ------ |
Ending balance                 |        |    800 |
------------------------------ | ------ | ------ |

- d. If 1,600 was received in January for services performed in January, what was the balance in Unearned Service Revenue at December 31, 2024?

In [10]:
ending_balance = 750

print(f"The balance of the Unearned Revenue account at December 31, was $ {ending_balance:,.0f}\n")
print("The transaction as given does not affect the Unearned Revenue account balance.")

The balance of the Unearned Revenue account at December 31, was $ 750

The transaction as given does not affect the Unearned Revenue account balance.

---